# fly.toml app configuration file generated for jewdick-app on 2025-09-17T16:57:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jewdick-app'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3000'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    method = 'get'
    path = '/'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
